/**
 * Fallback HTML for admin sections when fetch fails (file://).
 * Auto-built from pages/*.html — keep in sync.
 */
(function () {
  'use strict';
  window.SalintayoAdminPageHtml = [
    "<section id=\"section-dashboard\" class=\"admin-section is-visible admin-page admin-page--dashboard\" aria-labelledby=\"dash-heading\">\n  <header class=\"page-header\">\n    <h1 id=\"dash-heading\">Analytics Dashboard</h1>\n    <p>Select an analytics category to view detailed charts and metrics.</p>\n  </header>\n\n  <div class=\"dash-hub\">\n    <div class=\"dash-hub-grid\" id=\"dash-hub-grid\" role=\"list\"></div>\n    <p class=\"dash-data-source\" id=\"dash-data-source\"></p>\n  </div>\n\n  <div class=\"dash-modal-overlay\" id=\"dash-modal-overlay\" aria-hidden=\"true\">\n    <div class=\"dash-modal\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"dash-modal-title\">\n      <div class=\"dash-modal__header\">\n        <h2 id=\"dash-modal-title\">Analytics</h2>\n        <button type=\"button\" class=\"dash-modal__close\" id=\"dash-modal-close\" aria-label=\"Close\">&times;</button>\n      </div>\n      <div class=\"dash-modal__body\" id=\"dash-modal-body\"></div>\n    </div>\n  </div>\n</section>",
    "<section id=\"section-users\" class=\"admin-section admin-page admin-page--users\" aria-labelledby=\"users-heading\">\n  <header class=\"page-header\">\n    <h1 id=\"users-heading\">Users</h1>\n    <p>Rows load from Firestore learner profiles (<code class=\"page-code\">users/{uid}</code> by default, or <code class=\"page-code\">userProfiles</code> / others if <code class=\"page-code\">users</code> is empty). The Authentication user list is separate — profiles must be written by the app (or synced) to appear here.</p>\n  </header>\n  <div class=\"toolbar toolbar--users\">\n    <div class=\"admin-search\">\n      <svg class=\"admin-search__icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\">\n        <circle cx=\"11\" cy=\"11\" r=\"8\" />\n        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\" />\n      </svg>\n      <input type=\"search\" class=\"admin-input\" id=\"user-search\" placeholder=\"Search name or email…\" autocomplete=\"off\" />\n    </div>\n    <span class=\"page-meta\" id=\"users-meta\"></span>\n  </div>\n  <div class=\"panel panel__body--flush panel--raised\">\n    <div class=\"table-wrap\">\n      <table class=\"data-table data-table--users\" id=\"users-table\">\n        <thead>\n          <tr>\n            <th>Name</th><th>Email</th><th>Dialect</th><th>Status</th><th>Last active</th><th class=\"cell-actions\">Actions</th>\n          </tr>\n        </thead>\n        <tbody id=\"users-tbody\"></tbody>\n      </table>\n    </div>\n  </div>\n</section>",
    "<section id=\"section-bug-reports\" class=\"admin-section admin-page admin-page--bug-reports\" aria-labelledby=\"bug-reports-heading\">\n  <header class=\"page-header\">\n    <h1 id=\"bug-reports-heading\">Bug reports</h1>\n    <p>Bug reports from the SalinTayo app Help Center (<code class=\"page-code\">bugReports</code>, auto IDs).</p>\n  </header>\n  <div class=\"toolbar toolbar--users\">\n    <div class=\"admin-search\">\n      <svg class=\"admin-search__icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\">\n        <circle cx=\"11\" cy=\"11\" r=\"8\" />\n        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\" />\n      </svg>\n      <input type=\"search\" class=\"admin-input\" id=\"bug-report-search\" placeholder=\"Search email, type, or description…\" autocomplete=\"off\" />\n    </div>\n    <span class=\"page-meta\" id=\"bug-reports-meta\"></span>\n  </div>\n  <div class=\"panel panel__body--flush panel--raised\">\n    <div class=\"table-wrap\">\n      <table class=\"data-table\" id=\"bug-reports-table\">\n        <thead>\n          <tr>\n            <th>Submitted</th>\n            <th>User</th>\n            <th>Type</th>\n            <th>Platform</th>\n            <th>Description</th>\n          </tr>\n        </thead>\n        <tbody id=\"bug-reports-tbody\"></tbody>\n      </table>\n    </div>\n  </div>\n</section>",
    "<section id=\"section-feedback\" class=\"admin-section admin-page admin-page--feedback\" aria-labelledby=\"feedback-heading\">\n  <header class=\"page-header\">\n    <h1 id=\"feedback-heading\">Ratings &amp; feedback</h1>\n    <p>Ratings and comments from the app (<code class=\"page-code\">appFeedback</code>, auto IDs).</p>\n  </header>\n  <div class=\"toolbar toolbar--users\">\n    <div class=\"admin-search\">\n      <svg class=\"admin-search__icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\">\n        <circle cx=\"11\" cy=\"11\" r=\"8\" />\n        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\" />\n      </svg>\n      <input type=\"search\" class=\"admin-input\" id=\"feedback-search\" placeholder=\"Search email or comment…\" autocomplete=\"off\" />\n    </div>\n    <span class=\"page-meta\" id=\"feedback-meta\"></span>\n  </div>\n  <div class=\"panel panel__body--flush panel--raised\">\n    <div class=\"table-wrap\">\n      <table class=\"data-table\" id=\"feedback-table\">\n        <thead>\n          <tr>\n            <th>Submitted</th>\n            <th>User</th>\n            <th>Rating</th>\n            <th>Platform</th>\n            <th>Comment</th>\n          </tr>\n        </thead>\n        <tbody id=\"feedback-tbody\"></tbody>\n      </table>\n    </div>\n  </div>\n</section>"
  ];
})();
